### ISSUE TITLE
Provide stream parser

### ISSUE THREAD

**Issue by epage** [epage/anstyle#4]
This will be a building block for implicit conversions between formats

**Comment by epage** [comment]
See https://crates.io/crates/vt100

**Comment by epage** [comment]
Just came across [anes](https://lib.rs/crates/anes)

**Comment by Calder-Ty** [comment]
`cansi` looks like just what is needed, but unfortunately does not support truecolors.

**Comment by epage** [comment]
@Calder-Ty For roff's sake, that shouldn't matter as the initial version will more be a prototype for the sake of unblocking `clap_mangen`.  We can always iterate on it further,  extending what is supported, replacing the parser if needed, etc.

**Comment by Calder-Ty** [comment]
Leaving this here for future reference.

`anstyle-roff` provides a limited private implementation of a stream parser. I think next steps for this would be to find a better library than `cansi` for doing our parsing, as it doesn't support true colors or xterm colors. (Or push changes for cansi upstream). `vte` as you mentioned looks very promising, but would require more work on our part.

**Comment by epage** [comment]
With #41 and other PRs, we now have a parser.

I split updating anstyle-roff out into #63.
